Feature/sas tokens
gregsmi/hail pull request #8
Opened 2022-09-26 17:01 UTC by gregsmi

added Azure SAS token support by updating various URL and filesystem classes to handle and preserve query strings in file paths

2022-09-28 21:48 UTC, jeremiahwander requested changes

2022-09-28 21:48 UTC, jeremiahwander commented on hail/python/hail/fs/router_fs.py
> -                          *,
Curious why you removed the keyword arg requirement? Simply for brevity on [L258](https://github.com/gregsmi/hail/blob/65e7093261d50fae27c0a8b82ec6ef6e764133b7/hail/python/hail/fs/router_fs.py#L258)?

2022-09-28 21:48 UTC, jeremiahwander commented on hail/python/hailtop/aiocloud/aioazure/fs.py
> +    def get_account_container_and_name(url: str) -> Tuple[str, str, str, str]:
Maybe consider renaming to `get_account_container_name_and_token`, or `get_url_parts`. This method is specific to the Azure implementation and doesn't seem to be used outside of the aioazure.fs module.

2022-09-28 21:48 UTC, jeremiahwander commented on hail/python/hail/fs/router_fs.py
> +        async def ls_no_glob(*parts, params) -> List[StatResult]:
General comment on the use of the keyword `params`; is there a reason you used this as opposed to `query` when referring to the URI part? https://en.wikipedia.org/wiki/URL specifies `params` as a particular component of a well-formed URL that might be confusing in its use here. I know that's an invasive change, so wanted to get your take.

2022-09-28 21:48 UTC, jeremiahwander commented on hail/python/hailtop/aiocloud/aioazure/fs.py
> +    async def generate_sas_token(
Is there a use case for `generate_sas_token` other than to facilitate integration testing? If not, it feels odd to have it here, given we know the integration test is going to be run with the `DefaultAzureCredential` should we instead generate the SAS token in the test code?

2022-09-29 17:42 UTC, gregsmi commented on hail/python/hailtop/aiocloud/aioazure/fs.py
> +    async def generate_sas_token(
integration is actually run with a test service credential - I think overall it might be a useful function on the az interface

2022-09-29 17:50 UTC, gregsmi commented on hail/python/hail/fs/router_fs.py
> -                          *,
yeah, seemed like a dumb requirement for n internal function where the only callers were passing in identically named local parameters

2022-09-29 17:57 UTC, gregsmi commented on hail/python/hail/fs/router_fs.py
> +        async def ls_no_glob(*parts, params) -> List[StatResult]:
fixed

2022-09-29 17:58 UTC, gregsmi commented on hail/python/hailtop/aiocloud/aioazure/fs.py
> +    def get_account_container_and_name(url: str) -> Tuple[str, str, str, str]:
fixed

2022-09-29 21:56 UTC, jeremiahwander approved these changes

2022-10-03 20:19 UTC, jeremiahwander approved these changes

2022-10-03 20:19 UTC, jeremiahwander commented on hail/python/hailtop/aiocloud/aioazure/fs.py
> +            # We will accept it as a token string if it has at least 1 key-value pair of the form 'k=v'.
"We will accept it as a token string if it begins with at least 1 key-value pair of the form 'k=v'."

2022-11-02 02:59 UTC, merged